version: 2.1

#ORBS:
orbs:
  docker: circleci/docker@2.1.4
  heroku: circleci/heroku@2.0.0
  snyk: snyk/snyk@1.5.0

#JOBS: build, test, scan, publish, pull-and-deploy
jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0
      - image: cimg/postgres:13.3
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
  test:
    docker:
      - image: cimg/openjdk:17.0
      - image: cimg/postgres:13.3
    steps:
      - checkout
      - run:
          name: Test
          command: mvn test
  #sing 20240109
  scan:
    docker:
        - image: cimg/openjdk:17.0
        - image: cimg/postgres:13.3
    environment:
      IMAGE_NAME: anusuyadevi2024/group1module4project
    steps:
      - checkout
      - setup_remote_docker
      - docker/check
      - run: docker build -t $IMAGE_NAME .
      - snyk/scan:
          severity-threshold: high
          docker-image-name: $IMAGE_NAME

  #anu's portion below
  publish:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: anusuyadevi2024/group1module4project
          tag: "1.0.1"
      - docker/push:
          image: anusuyadevi2024/group1module4project
          tag: "1.0.1"


#WORKFLOW: ci_flow = dev branch & cicd_flow = release branch
workflows:
  ci_flow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - develop
      - test:
          filters:
            branches:
              only:
                - develop
          requires:
            - build
      - scan:
          filters:
            branches:
              only:
                - develop
          requires:
            - test

  cicd_flow:
    jobs:
      #lauren's portion below
      - build:
          filters:
            branches:
              only:
                - release
      - test:
          filters:
            branches:
              only:
                - release
          requires:
            - build
      - scan:
          filters:
            branches:
              only:
                - develop
          requires:
            - test
      - publish:
          filters:
            branches:
              only:
                - release
          requires:
            - scan
      - heroku/push-docker-image:
          app-name: group1module4
          pre-deploy:
            - setup_remote_docker
          filters:
            branches:
              only:
                - release
          requires:
            - publish
